### ISSUE TITLE
line 18 invalid syntax

### ISSUE THREAD

**Issue by jsvalderrama** [Lodour/TeamViewer-ID-Switcher#1]
Hello, 
I wonder if you have made any updates on your code, because I am trying to use it on my Mac with TeamViewer 15+ but it shows an error running the script.
Thanks in advance for your answer.

**Comment by Lodour** [comment]
Hi, there is a type annotation at Line 18, which is a new feature in Python 3 I think.
If you are using Python 2, please remove all annotations before running the script.
E.g, change `def foo(bar: int)` to `def foo(bar)`

**Comment by jsvalderrama** [comment]
Hello, 
Thanks for your answer. I have updated my Python  3.9.4 and I still have the error, so I removed the script like you suggested on lines 18 and 23, but in line 26 I still have an error and I don't know what to change.

**Comment by Lodour** [comment]
Can you please post the detailed error?

**Comment by jsvalderrama** [comment]
File "switch.py", line 26
    data = re.sub(rb'(IOPlatformExpert)\w{6}', rb'\g<1>%s' %)
                                            ^
SyntaxError: invalid syntax

**Comment by Lodour** [comment]
It seems that you are still running with Python 2.
Can you please double check your env, like `sudo python -V`?

**Comment by jsvalderrama** [comment]
Hello, here is my last test and the error. I'm running it on python 3.9 as you will see. Please advice

% /usr/local/opt/python@3.9/bin/python3.9 /Users/jsv/switch.py

The following binaries will be modified:
 - /Applications/TeamViewer.app/Contents/MacOS/TeamViewer
 - /Applications/TeamViewer.app/Contents/MacOS/TeamViewer_Service

Press [Enter] to continue...

Using platform "651592" and serial "19FB25A9".
Traceback (most recent call last):
  File "/Users/jsv/switch.py", line 50, in <module>
    main()
  File "/Users/jsv/switch.py", line 45, in main
    patch(binary, platform, serial)
  File "/Users/jsv/switch.py", line 28, in patch
    with target.open('wb') as f:
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/Applications/TeamViewer.app/Contents/MacOS/TeamViewer'

**Comment by Lodour** [comment]
you need to run with sudo

**Comment by jsvalderrama** [comment]
my bad. thanks you very much
